const mongoose = require("mongoose");

const dailyPosterSchema = new mongoose.Schema(
  {
    date: {
      type: String,
      required: true,
      unique: true,
    },

    occasion: {
      type: String,
      required: true,
    },

    category: {
      type: String,
      default: "General",
    },

    message: {
      type: String,
      required: true,
    },

    status: {
      type: String,
      enum: ["generated", "approved", "published"],
      default: "generated",
    },

    storyImage: {
      type: String,
      default: "",
    },

    squareImage: {
      type: String,
      default: "",
    },

    autoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("DailyPoster", dailyPosterSchema);