const cron = require("node-cron");
const DailyPoster = require("../models/DailyPoster");
const { getTodaySpecialDay } = require("./specialDays");

async function generateDailyPosterData() {
  try {
    const now = new Date();

    const date = `${now.getFullYear()}-${String(
      now.getMonth() + 1
    ).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;

    const existing = await DailyPoster.findOne({ date });

    if (existing) {
      console.log(`Poster already exists for ${date}`);
      return existing;
    }

    const special = getTodaySpecialDay();

    const poster = await DailyPoster.create({
      date,
      occasion: special.occasion,
      category: special.category,
      message: special.message,
      autoGenerated: true,
    });

    console.log(`✅ Daily poster data generated: ${special.occasion}`);

    return poster;
  } catch (error) {
    console.error("❌ Daily poster generation error:", error);
  }
}

/*
  Every day at 7:00 AM
*/
function startPosterScheduler() {
  cron.schedule(
    "0 7 * * *",
    async () => {
      console.log("🎨 Running G2G Daily Poster Scheduler...");
      await generateDailyPosterData();
    },
    {
      timezone: "Asia/Kolkata",
    }
  );

  console.log("🟢 G2G Daily Poster Scheduler started");
}

module.exports = {
  startPosterScheduler,
  generateDailyPosterData,
};